data = {
  documentation: "https://opencagedata.com/api",
  licenses: [
    {
      name: "see attribution guide",
      url: "https://opencagedata.com/credits",
    },
  ],
  rate: {
    limit: 2500,
    remaining: 2496,
    reset: 1621641600,
  },
  results: [
    {
      bounds: {
        northeast: {
          lat: 13.1436649,
          lng: 77.7840515,
        },
        southwest: {
          lat: 12.8340125,
          lng: 77.4601025,
        },
      },
      components: {
        "ISO_3166-1_alpha-2": "IN",
        "ISO_3166-1_alpha-3": "IND",
        _category: "place",
        _type: "city",
        city: "Bengaluru",
        continent: "Asia",
        country: "India",
        country_code: "in",
        county: "Bangalore North",
        state: "Karnataka",
        state_code: "KA",
        state_district: "Bangalore Urban",
      },
      confidence: 3,
      formatted: "Bengaluru, Bangalore North, India",
      geometry: {
        lat: 12.9791198,
        lng: 77.5912997,
      },
    },
    {
      bounds: {
        northeast: {
          lat: 21.9873687,
          lng: -100.8589592,
        },
        southwest: {
          lat: 21.9803571,
          lng: -100.8656606,
        },
      },
      components: {
        "ISO_3166-1_alpha-2": "MX",
        "ISO_3166-1_alpha-3": "MEX",
        _category: "road",
        _type: "road",
        continent: "North America",
        country: "Mexico",
        country_code: "mx",
        county: "Villa de Reyes",
        hamlet: "Valle de San Francisco",
        industrial: "Parque Industrial Logisik II",
        postcode: "79526",
        road: "Bangalore",
        state: "San Luis Potosi",
      },
      confidence: 9,
      formatted:
        "Bangalore, Parque Industrial Logisik II, 79526 Valle de San Francisco, San Luis Potosi, Mexico",
      geometry: {
        lat: 21.984304,
        lng: -100.8627452,
      },
    },
    {
      bounds: {
        northeast: {
          lat: 51.4181327,
          lng: -0.0836785,
        },
        southwest: {
          lat: 51.4180175,
          lng: -0.083845,
        },
      },
      components: {
        "ISO_3166-1_alpha-2": "GB",
        "ISO_3166-1_alpha-3": "GBR",
        _category: "building",
        _type: "building",
        building: "Bangalore",
        city: "London",
        city_district: "London Borough of Croydon",
        continent: "Europe",
        country: "United Kingdom",
        country_code: "gb",
        postcode: "SE19 3AY",
        road: "Bedwardine Road",
        state: "England",
        state_code: "ENG",
        state_district: "Greater London",
        suburb: "Upper Norwood",
      },
      confidence: 10,
      formatted: "Bangalore, Bedwardine Road, London SE19 3AY, United Kingdom",
      geometry: {
        lat: 51.4180786,
        lng: -0.0837641,
      },
    },
    {
      bounds: {
        northeast: {
          lat: 43.6045428,
          lng: 1.4536901,
        },
        southwest: {
          lat: 43.6044428,
          lng: 1.4535901,
        },
      },
      components: {
        "ISO_3166-1_alpha-2": "FR",
        "ISO_3166-1_alpha-3": "FRA",
        _category: "commerce",
        _type: "restaurant",
        city: "Toulouse",
        continent: "Europe",
        country: "France",
        country_code: "fr",
        county: "Haute-Garonne",
        municipality: "Toulouse",
        neighbourhood: "Les Chalets - Saint-Aubin - Saint-Étienne",
        political_union: "European Union",
        postcode: "31000",
        restaurant: "Le Bangalore",
        road: "Rue de la Colombette",
        state: "Occitania",
        state_code: "OCC",
        suburb: "Toulouse Centre",
      },
      confidence: 9,
      formatted: "Le Bangalore, Rue de la Colombette, 31000 Toulouse, France",
      geometry: {
        lat: 43.6044928,
        lng: 1.4536401,
      },
    },
    {
      bounds: {
        northeast: {
          lat: 52.9651703,
          lng: -1.1227278,
        },
        southwest: {
          lat: 52.965062,
          lng: -1.1228849,
        },
      },
      components: {
        "ISO_3166-1_alpha-2": "GB",
        "ISO_3166-1_alpha-3": "GBR",
        _category: "building",
        _type: "building",
        building: "Bangalore",
        city: "Nottingham",
        continent: "Europe",
        country: "United Kingdom",
        country_code: "gb",
        house_number: "28",
        neighbourhood: "Thorneywood",
        postcode: "NG3 2PT",
        road: "Thorney Hill",
        state: "England",
        state_code: "ENG",
        state_district: "East Midlands",
        suburb: "Sneinton",
      },
      confidence: 10,
      formatted:
        "Bangalore, 28 Thorney Hill, Nottingham NG3 2PT, United Kingdom",
      geometry: {
        lat: 52.9651162,
        lng: -1.1228064,
      },
    },
    {
      bounds: {
        northeast: {
          lat: 50.8461595,
          lng: 0.5028916,
        },
        southwest: {
          lat: 50.8460954,
          lng: 0.5027427,
        },
      },
      components: {
        "ISO_3166-1_alpha-2": "GB",
        "ISO_3166-1_alpha-3": "GBR",
        _category: "building",
        _type: "building",
        building: "Bangalore",
        city: "Rother",
        continent: "Europe",
        country: "United Kingdom",
        country_code: "gb",
        county: "East Sussex",
        county_code: "ESX",
        postcode: "TN40 2LB",
        road: "Hastings Road",
        state: "England",
        state_code: "ENG",
        state_district: "South East England",
        suburb: "Glyne Gap",
        town: "Bexhill-on-Sea",
      },
      confidence: 10,
      formatted:
        "Bangalore, Hastings Road, Bexhill-on-Sea TN40 2LB, United Kingdom",
      geometry: {
        lat: 50.8461274,
        lng: 0.5028172,
      },
    },
    {
      bounds: {
        northeast: {
          lat: 50.8173673,
          lng: 4.4214862,
        },
        southwest: {
          lat: 50.8172673,
          lng: 4.4213862,
        },
      },
      components: {
        "ISO_3166-1_alpha-2": "BE",
        "ISO_3166-1_alpha-3": "BEL",
        _category: "commerce",
        _type: "restaurant",
        continent: "Europe",
        country: "Belgium",
        country_code: "be",
        county: "Brussels-Capital",
        county_code: "BRU",
        house_number: "1629",
        political_union: "European Union",
        postcode: "1160",
        quarter: "Square Baron Hankar",
        region: "Brussels-Capital",
        restaurant: "Bangalore",
        road: "Chaussée de Wavre - Waversesteenweg",
        town: "Auderghem - Oudergem",
      },
      confidence: 9,
      formatted:
        "Bangalore, Chaussée de Wavre - Waversesteenweg 1629, 1160 Auderghem - Oudergem, Belgium",
      geometry: {
        lat: 50.8173173,
        lng: 4.4214362,
      },
    },
    {
      bounds: {
        northeast: {
          lat: 41.149307,
          lng: -73.24582,
        },
        southwest: {
          lat: 41.1490878,
          lng: -73.246107,
        },
      },
      components: {
        "ISO_3166-1_alpha-2": "US",
        "ISO_3166-1_alpha-3": "USA",
        _category: "commerce",
        _type: "restaurant",
        city: "Fairfield",
        continent: "North America",
        country: "United States",
        country_code: "us",
        county: "Fairfield County",
        house_number: "1342",
        postcode: "06834",
        restaurant: "Bangalore",
        road: "Kings Highway Cutoff",
        state: "Connecticut",
        state_code: "CT",
      },
      confidence: 9,
      formatted:
        "Bangalore, 1342 Kings Highway Cutoff, Fairfield, CT 06834, United States of America",
      geometry: {
        lat: 41.1492183,
        lng: -73.2459635,
      },
    },
  ],
  status: {
    code: 200,
    message: "OK",
  },
  stay_informed: {
    blog: "https://blog.opencagedata.com",
    twitter: "https://twitter.com/OpenCage",
  },
  thanks: "For using an OpenCage API",
  timestamp: {
    created_http: "Fri, 21 May 2021 04:58:29 GMT",
    created_unix: 1621573109,
  },
  total_results: 8,
};
